
name: Commit Testing

on: [push]

jobs:
  buildJar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: Set up PATH
        run: |
          echo "${ANDROID_HOME}/build-tools/30.0.1" >> $GITHUB_PATH
          echo "${JAVA_HOME}/Eclipse Foundation/jdk-17.0.3+7/" >> $GITHUB_ENV
      - name: Set up JDK 17
        uses: actions/setup-java@v3.5.1
        with:
          java-version: 17
          distribution: temurin
      - name: Build mod jar
        run: ./gradlew deploy
      - name: Upload built jar file
        uses: actions/upload-artifact@v3.1.0
        with:
          name: ${{ github.event.repository.name }}
          path: build/libs/${{ github.event.repository.name }}.jar