
name: Commit Testing

on: [push]

jobs:
  buildJar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up PATH
        run: |
          echo "${ANDROID_HOME}/build-tools/30.0.1" >> $GITHUB_PATH
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Build mod jar
        run: ./gradlew deploy
      - name: Upload built jar file
        uses: actions/upload-artifact@v3.1.0
        with:
          name: ${{ github.event.repository.name }}
          path: build/libs/${{ github.event.repository.name }}.jar